B403Blog/B403Blog/Controllers/EtiketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace B403Blog.Controllers
{
    using Models;
    public class EtiketController : Controller
    {
        // GET: Etiket
        B403BlogContext context = new B403BlogContext();
        public ActionResult Index(int id)
        {
            return View(id);
        }

        public PartialViewResult EtiketlerWidget()
        {
            return PartialView(context.Etikets.ToList());
        }
        public ActionResult MakaleListele(int id)
        {
            //any metodu icerde yaptigimiz kontrol var mi diye kontrol eder varsa true yoksa false dondurur
            var data = context.Makales.Where(x => x.Etikets.Any(y=>y.EtiketId==id)).ToList();
            return View("MakaleListeleWidget", data);
        }

    }
}

B403Blog/B403Blog/Controllers/KategoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace B403Blog.Controllers
{
    using Models;
    public class KategoriController : Controller
    {
        B403BlogContext context = new B403BlogContext();

        // GET: Kategori
        public ActionResult Index(int id)
        {
            return View(id);
        }

        public PartialViewResult KategoriWidget()
        {
            return PartialView(context.Kategoris.ToList());
        }

        public ActionResult MakaleListele(int id) {
            var data = context.Makales.Where(x => x.KategoriId == id).ToList();
            return View("MakaleListeleWidget",data);
        }
        
    }
}

B403Blog/B403Blog/Views/Shared/Arama.cshtml
@{ 

    Layout = null;


}

<div class="sidebox widget">
    <h3 class="widget-title section-title">Ara</h3>
    <form class="searchform" action="/Home/Ara" method="post">
        <label><i class="icon-search"></i></label>
        <input type="text" id="s2" name="content" value="Ara" onfocus="this.value = ''" onblur="    this.value = 'Ara'" />
        <button type="submit" class="btn">Bul</button>
    </form>
</div>

B403Blog/B403Blog/Views/Shared/MakaleListeleWidget.cshtml
@model IEnumerable<B403Blog.Models.Makale>


@{ 
    Layout = null;
}




@helper IcerikKisalt(string metin)
{
if (metin.Length > 300)
{
        <p>@metin.Substring(0, 300)</p>
}
else
{
        @metin
}
}
@* burada custom bir helper olusturduk. Bu helper eger metin 300 karakterden kisaysa metini dondurecek eger uzunsa
    metini bolup dondurecek. Boylece metin eger 300 karakterden kisaysa hata vermesini engellemis oldurk. *@


<div class="blog-posts col-blog">
    @foreach (B403Blog.Models.Makale mkl in Model)
    {

        <div class="post row">
            <div class="col-sm-4">
                <figure>
                    <a href="blog-post.html">
                        <div class="text-overlay">
                            <div class="info"><span>Hepsini Oku</span></div>
                        </div>
                        <img src="@mkl.Resim.OrtaBoyut" alt="" />
                    </a>
                </figure>
            </div>
            <div class="col-sm-8 post-content">
                <div class="meta">
                    <span class="date">@mkl.EklenmeTarihi.ToShortDateString()</span>
                    <span class="comments"><a href="#">@mkl.Yorums.Count <i class="icon-chat-1"></i></a></span>
                </div>
                <h2 class="post-title"><a href="/Makale/Detay/@mkl.MakaleId">@mkl.Baslik</a></h2>

                <p>@IcerikKisalt(mkl.Icerik)</p>
            </div>
        </div>

    }


</div>

B403Blog/B403Blog/Views/Shared/SiteHakkinda.cshtml
<div class="sidebox widget">
    <h3 class="widget-title section-title">Site Hakkında</h3>
    <p>Bu blog yazılım ve bilgisayar mühendisliği alanlarına hitap eden ve neredeyse tamamı ingilizce kaynaklardan çeviri olan makaleler içeren, eğitici içerikler barındıran bir web sayfasıdır.
    Dileyen herkes bu bloğa yazı yazabilir fakat içerikler kontrol edileceğinden dolayı yazılan makalelerin özenle yazılmasını sizden önemle rica ederim.
    </p>
    <ul class="social">
        <li><a href="#"><i class="icon-s-rss"></i></a></li>
        <li><a href="#"><i class="icon-s-twitter"></i></a></li>
        <li><a href="#"><i class="icon-s-facebook"></i></a></li>
        <li><a href="#"><i class="icon-s-pinterest"></i></a></li>
        <li><a href="#"><i class="icon-s-linkedin"></i></a></li>
        <li><a href="#"><i class="icon-s-dribbble"></i></a></li>
        <li><a href="#"><i class="icon-s-flickr"></i></a></li>
    </ul>
    <div class="clearfix"></div>
</div>

B403Blog/B403Blog/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="style/images/favicon.png">
    <title>B403 Blog - @ViewBag.Title</title>
    <!-- Bootstrap core CSS -->
    <link href="/Content/style/css/bootstrap.min.css" rel="stylesheet">
    <link href="/Content/style/css/plugins.css" rel="stylesheet">
    <link href="/Content/style.css" rel="stylesheet">
    <link href="/Content/style/css/color/red.css" rel="stylesheet">
    <link href="/Content/style/type/bebas.css" rel="stylesheet">
    <link href="/Content/style/type/fontello.css" rel="stylesheet">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
          <script src="style/js/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
          <![endif]-->
    @RenderSection("head", false)
</head>
<body>
   
    <div class="body-wrapper">
        <div class="navbar default">
            <div class="navbar-header">               
                <div class="container">
                    <div class="basic-wrapper">
                        <a class="btn responsive-menu pull-right" data-toggle="collapse" data-target=".navbar-collapse"><i></i></a>
                        <div class="navbar-brand"><a href="index.html"><img src="style/images/logo.png" alt="" data-src="style/images/logo.png" data-ret="style/images/logo@2x.png" class="retina" /></a></div>
                    </div>
                    <nav class="collapse navbar-collapse pull-right">
                        <ul class="nav navbar-nav">
                            <li><a href="index.html">Home</a></li>
                            <li class="current dropdown">
                                <a href="#" class="dropdown-toggle js-activated">Journal</a>
                                <ul class="dropdown-menu">
                                    <li><a href="blog.html">List View</a></li>
                                    <li><a href="blog2.html">Classic View</a></li>
                                    <li><a href="blog3.html">Grid View 2 Columns</a></li>
                                    <li><a href="blog4.html">Grid View 3 Columns</a></li>
                                    <li><a href="blog-post.html">Blog Post</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle js-activated">Our Works</a>
                                <ul class="dropdown-menu">
                                    <li><a href="portfolio.html">Classic Portfolio</a></li>
                                    <li><a href="portfolio2.html">Fullscreen Portfolio</a></li>
                                    <li><a href="portfolio-post.html">Post with Images</a></li>
                                    <li><a href="portfolio-post2.html">Post with Columns</a></li>
                                    <li><a href="portfolio-post3.html">Post with Video</a></li>
                                    <li><a href="portfolio-post4.html">Post with Slider</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle js-activated">Pages</a>
                                <ul class="dropdown-menu">
                                    <li><a href="about.html">About</a></li>
                                    <li><a href="services.html">Services</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle js-activated">Features</a>
                                <ul class="dropdown-menu">
                                    <li><a href="elements.html">Elements</a></li>
                                    <li><a href="headings.html">Headings</a></li>
                                    <li><a href="pricing.html">Pricing Tables</a></li>
                                    <li><a href="flat-icons.html">Flat Icons</a></li>
                                    <li><a href="font-icons.html">Font Icons</a></li>
                                </ul>
                            </li>
                            <li><a href="contact.html">Contact</a></li>
                            <li class="dropdown social-dropdown pull-right">
                                <div class="share btn btn-default dropdown-toggle" data-toggle="dropdown"><i class="icon-heart-1"></i></div>
                                <ul class="button-group dropdown-menu dropdown-menu-right share-links">
                                    <li><a href="#" class="btn"><i class="icon-s-facebook"></i></a></li>
                                    <li><a href="#" class="btn"><i class="icon-s-twitter"></i></a></li>
                                    <li><a href="#" class="btn"><i class="icon-s-pinterest"></i></a></li>
                                </ul>
                            </li>
                            <!--/social-dropdown -->
                        </ul>
                        <!--/.navbar-nav -->
                    </nav>
                    <!--/.nav-collapse -->
                </div>
                <!--/.container -->
            </div>
            <!--/.navbar-header -->
        </div>
        <!--/.navbar -->
        <div class="offset"></div>
        

        <div class="container inner">
            
            <div class="row">
                <div class="col-sm-8 content">
                    @RenderBody()
                </div>
                <!-- /.content -->
                <aside class="col-sm-4 sidebar lp30">
                    @{
                        Html.RenderAction("PopulerMakalelerWidget", "Home");
                    }@*bu sekilde basinca her sayfada olacak demek bu*@
                    <!-- /.widget -->
                    @{
                        Html.RenderPartial("SiteHakkinda");
                    }
                    
                    <!-- /.widget -->
                    @{
                         Html.RenderPartial("Arama", "Home");

                    }
                    <!-- /.widget -->
                    
                    <!-- /.widget -->
                    @{
                        Html.RenderAction("KategoriWidget", "Kategori");

                    }
                   
                    <!-- /.widget -->
                    @{
                        Html.RenderAction("EtiketlerWidget","Etiket");

                    }


                   
                    <!-- /.widget -->
                </aside>
                <!-- /.col-sm-4 .sidebar -->

            </div>
            <!-- /.row -->
        </div>
        <!--/.container -->
        <footer class="footer black-wrapper">
            <div class="container inner">
                <div class="row">

                    <div class="col-sm-3">
                        <div class="widget">
                            <h3 class="widget-title">Popular Posts</h3>
                            <ul class="post-list">
                                <li>
                                    <div class="icon-overlay"> <a href="blog-post.html"><img src="/Content/style/images/art/a1.jpg" alt="" /> </a> </div>
                                    <div class="meta">
                                        <h5><a href="blog-post.html">Magna Mollis Ultricies</a></h5>
                                        <em>3th Oct 2012 <span class="comments"><a href="#">8 <i class="icon-chat-1"></i></a></span></em>
                                    </div>
                                </li>
                                <li>
                                    <div class="icon-overlay"> <a href="blog-post.html"><img src="/Content/style/images/art/a2.jpg" alt="" /> </a> </div>
                                    <div class="meta">
                                        <h5><a href="blog-post.html">Ornare Nullam Risus</a></h5>
                                        <em>28th Sep 2012 <span class="comments"><a href="#">5 <i class="icon-chat-1"></i></a></span></em>
                                    </div>
                                </li>
                                <li>
                                    <div class="icon-overlay"> <a href="blog-post.html"><img src="/Content/style/images/art/a3.jpg" alt="" /> </a> </div>
                                    <div class="meta">
                                        <h5><a href="blog-post.html">Euismod Nullam</a></h5>
                                        <em>15th Aug 2012 <span class="comments"><a href="#">9 <i class="icon-chat-1"></i></a></span></em>
                                    </div>
                                </li>
                            </ul>
                            <!-- /.post-list -->
                        </div>
                        <!-- /.widget -->
                    </div>
                    <!-- /column -->

                    <div class="col-sm-3">
                        <div class="widget">
                            <h3 class="widget-title">About Us</h3>
                            <p>Aenean lacinia bibendum nulla sed leo posuere erat a ante venenatis dapibus posuere velit aliquet. Donec ullamcorper metus auctor fringi. Nullam quis risus. </p>
                            <p>Vestibulum id ligula porta  euismod semper. Maecenas faucibus mollis.</p>
                            <div class="divide5"></div>
                            <ul class="social">
                                <li><a href="#"><i class="icon-s-rss"></i></a></li>
                                <li><a href="#"><i class="icon-s-twitter"></i></a></li>
                                <li><a href="#"><i class="icon-s-facebook"></i></a></li>
                                <li><a href="#"><i class="icon-s-pinterest"></i></a></li>
                                <li><a href="#"><i class="icon-s-linkedin"></i></a></li>
                            </ul>
                        </div>
                        <!-- /.widget -->
                    </div>
                    <!-- /column -->

                    <div class="col-sm-3">
                        <div class="widget">
                            <h3 class="widget-title">Get In Touch</h3>
                            <p>Fusce dapibus, tellus commodo, tortor mauris condimentum utellus fermentum, porta sem malesuada magna. Sed posuere consectetur est at lobortis.</p>
                            <div class="contact-info">
                                <i class="icon-location"></i> Moonshine St. 14/05 Light City <br />
                                <i class="icon-phone"></i>+00 (123) 456 78 90 <br />
                                <i class="icon-mobile"></i>+80 (547) 455 47 54 <br />
                                <i class="icon-mail"></i> <a href="first.last%40email.html">first.last@email.com</a>
                            </div>
                        </div>
                    </div>
                    <!-- /column -->

                    <div class="col-sm-3">
                        <div class="widget">
                            <h4 class="widget-title">Tags</h4>
                            <ul class="tag-list">
                                <li><a href="#">Web</a></li>
                                <li><a href="#">Photography</a></li>
                                <li><a href="#">Illustation</a></li>
                                <li><a href="#">Fun</a></li>
                                <li><a href="#">Blog</a></li>
                            </ul>
                            <!-- /.tag-list -->
                        </div>
                        <!-- /.widget -->

                        <div class="widget">
                            <h4 class="widget-title">Categories</h4>
                            <ul class="circled">
                                <li><a href="#">Web Design (21)</a></li>
                                <li><a href="#">Photography (19)</a></li>
                                <li><a href="#">Graphic Design (16)</a></li>
                            </ul>
                        </div>
                        <!-- /.widget -->

                    </div>
                    <!-- /column -->

                </div>
                <!-- /.row -->
            </div>
            <!-- .container -->

            <div class="sub-footer">
                <div class="container">
                    <p class="pull-left">© 2015 Keepsake. All rights reserved. Theme by <a href="http://elemisfreebies.com/">elemis</a>.</p>
                    <ul class="footer-menu pull-right">
                        <li><a href="#">Home</a></li>
                        <li><a href="#">About</a></li>
                        <li><a href="#">Portfolio</a></li>
                        <li><a href="#">Blog</a></li>
                        <li><a href="#">Contact</a></li>
                    </ul>
                </div>
            </div>
        </footer>
        <!-- /footer -->
    </div>
    <!--/.body-wrapper -->
    <script src="/Content/style/js/jquery.min.js"></script>
    <script src="/Content/style/js/bootstrap.min.js"></script>
    <script src="/Content/style/js/plugins.js"></script>
    <script src="/Content/style/js/scripts.js"></script>
</body>
</html>